language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: nodejs-shareyouridea
  api_key:
    secure: cEYGX9237D27OyxzuCQ2FKpR2ybu7oaHLWsZpDoFyaw7QUqi/pPtprxfGVdv0Eq8ee35BJqlxJhTZD62nwy7qCEmzmCTBgTdFn9BkWtHSpzv4l7Ftv1tg7T0R/+IRFtHYSTdICE37QpwIqaLScWHHWlrRsX+KlBOMVkdKMNhme4XFQU/GZwShvWDEHWmuCKErRqzTptoJroW4CJA7J+f2AQLTe5oMpq/dyYvtcr/VSspVnUCDytyYDtvBqDsHwVkb5qdtXhr/2LTpmH3eyM0pN8rNCHtR0385cHQfTGm+XbZY+48ShtBOLLxF+v5xaz4n/F5LL7Y8XpgXY1jY3JRbkFrWqifF9XXoqxQ3ouWYlVMdxPAZpoUCMZIcHOgbf7HALEui2oTiT/qhFcHuWxeReGeRb5tFucglQe2x7xqXlhU8JrBtkIRg525jy2Tv8Rmgxky5C79efz0YMMhgUbtonyEZKraLOkaii66IqhduGRNQQBLrui2iATesPj/4InhFnWZ+evbGIkuYsc79+aLeRKgojRzfpcbAWNGncM5DBAp6S+8oCbjs/mUhNJyXJNzlXBo2wT9ac6R5PJSBmGpnFlTa04pUilsxnf9A3YCPxPODZQvgzIqGaL0Rp5RKP8rw01tz3LGq0lC5spGMghc4el9HE0jPzFbPPzV6pCYFjY=
