language: node_js
node_js:
- stable
deploy:
  skip_cleanup: true
  provider: heroku
  app: nodejs-shareyouridea
  api_key:
    secure: HixU7nhheaKWJIjNMHF9yePbAFY2Y4TcXwaSnuMfs0jq3g13ukRthiAcNBYsYPGYXwJUq6bFxcuZguSppwFD7L4U6AcX9uqo+8l4ktmpfK866Wig27G8na+UdtTr3df+Y1yJP+YIZTxFJ10G2pfMzTMnDhJ1zQBia39KCib/MbcehH9XLZUbn14tgyFRYr9ZYZncPd08Q1tXo06qp+YnsRgAyV+yZvYIci/F7wnCulWphfONl7eyikNJiuNi/mL974b2OqbVBG2/TwQi4rC30DdRVwtRc05xP20C7RrOmrU22bdwr9iNVELLudsBiNsKEKo1P6QBwrJtLBoM07XsraMBcVBVGUYF9TiUg0EVSpoRb5gBngdcNg6H+t0VFikU7lMO+OOeTDeGWhWEpZQg8gU5z/Qqsw0sCsslDVVuQE51xjgcZRBQUQcGtBMfDOIogCALpmaaBPIZ3thUgAgBBzIYI46blvdnJ+eEthiaNU4CRU7poPUCN0stcaxmYM1N0WfMhle5dISET4a7wMxUM/0ydp25YgAsvC98cWoTWGgDQiKADW4iMehzlsMZLSLx940bA+H6+4KeQj9Z5te7W8nkrrMhe1ITcMfp6MqjZ6aGYhrmyfposOWTz1hHo9Y/Z6/tZWY28xiCP3A0zAWmYY7+fnIX8Ukb4E+c2hiSCfI=
