language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: nodejs-shareyouridea
  api_key:
    secure: Dk2t/lnAJKg/7Amt+1Z3kAiByUdEIDAIBh1WTHcsvvBCnvsoQQzF0DZGsLMa3077HN07aRVGVZe4keNCa6TeOKdsbXgv7uu4+Lf85a8f744AgDi8Cpr4QiWqvbNwzec0hdP0p8xhaQuPzkDJBldA5scPyEkMNlCeJ8d7rFTtD3s4WF6a1ccMgMGbl2odfRmO1rXgRf0GweIx7RdiTBysvNNTLIgkbGEFPfaiRH/rr2wFZ8hLh4HitsrXoq/wTi2ZMr+o0y2fI/1swYQ6ClCj5WYdnk++bIfncm45xQAF8bzb0NSqDOxafJR+sqE6NmSF8l+oPTgFdrND4ANCxFjoWAAMYBxb/oc36zwTZMvnCzU8HFdIOf+O6EbVQL+XLscoMCChf94SZ6qKD4OWVTA7jTv0IXKF8coUCLSOObyJZnLQj+5zpSCefCykZB2BPH1RjwlKvQlagttCi0UcVSSY0wfZNYzDJ1VKJRa5Kflu4beX61d87QUQyn0fvConU0zMGEmHDhOKB3riiVRNAg2ospqac4ZjhOLlgsu+flIxdkAzxARhns7hLi4e2X8KpEjXvhqNOM1aL09yihX1gPrX2U4LgxZZ8biIJ3ZBxWt2SmFukdYUboysqGe3cjtv9dOarY/eBknbbYgPAQiHl6AlCA1mzTVDQrVS/NWZ4n5acvs=
