language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: nodejs-shareyouridea
  api_key:
    secure: bun5QX+RjwOGzvWNys4+K9QOsTUg2/DfnVkL7do1wAzlf7bfS60cm6intjp9Gr+Rsk97BugNCObqq8VZvdHra67tb+Dmr7NIYxCIlgNMTBikYAYrgqd2fuISeTwYtQ0Z1UnRv1TpopUCqSwVu364fbhx9mA4XagHc7dZoFjAwx1vlzq9UUrx4wwHRMiC+Vny+o+iXNyHK81Zvsq/kHiEojj8KSdsQPiLLA7rpWfcqAZbGOLsocOrlpN6irVLN1nc9eo69Rsu+pH0PQ0K/9+5FQcKcbwETiU0KbtX1KGxWYVI4xOAk5fQONNCu3pHx09MvOMfmkQt9kJOC7I+eVz7SVJJ7XziHbraHQIUULTaJxbVS0AV+F1ekyWf0Sba3iP3ftsmVvJLC+56h72qYg1BSGf+7pF1ijXKX1obiwoyyXG4+LZ4fu8gpfaOoQobWCcxyf7S34STbwVakP5gMP9rE/GmndyNyBWkZVNqHCaRrPz5ck+lKX8gV90YErvENWDwxdO5qvWfyZGrk5JQeln0CQdgYmXV60hljMU6s7iq7ftXcBcwENLloE8xjGkSaBvGsQGyJqVxZ05/PU4kkduexrmmKYWn3OvJHF/hRF+4nCOsxvcIs/F+cWDiJ1YtYVY9Nehjl6n95EIW1guLE/dc1Nc2txUPUSYbfmaIZLvYmSg=
