language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: nodejs-shareyouridea
  api_key:
    secure: TZz/vXl90kcKGaLF32wXWAHgNm1sA4aCyXOxEqHWmvqf0RpxVa2dpefDPjcgCowWUWJ01P1b0ZojAKBrBIGud+Ku7NzGmDBdatwODis126fE0BlNcSGeMVdU05vV1RZJzebsWqke1ZPS4tAREQiw9TmngCEBMc3lWKfsLZ5M+Soo4LKd+/wjGAM2pmD0nsUuMQYsvKEDZhobrS+vca0SnMiYxCcwiMp3Uh7dUu3fCRSHMKqno9Mx6GfzYewJracwaEVMco8ISLigGWSdxbuGWMynng2LdNjgE7i7qCURCHA6WEBpq2kRzEJNJw5mWUCUwl+n5Y1IRT2OibkqnCBXF33Qm3XwBOmXdhkzf6Z8gR68jVbchQM4tIfeHtl517ZcEBD31tTFG6C5mYiZ3bENAFRanKO+7QeXdrVFGShsTxwhjQF06fPj16Rd6/6iTk3j8bsJm7SUP4XcYuksdt8G+OZIbuTu1T+P/ZOnaCV1qL6jLZs4M8NzCbbu06Y1vWRS2OU6jmtPmcNA7D3L4d10lxSQH0f5JVI7QBbtHtQOGIK0zREdfhPIy/DHoR22WKeqyEB1EZonmR4iHJ6S2v39QvbTFUUSS0+W08k8f5dj7BbCbeW0K0VClyi8cKmCG2JPiPLjuk0u1hu660xS20efyGWfX1kWrDr1N0krlcn/A98=
